{"cat": {"noun": ["A small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws. It is widely kept as a pet or for catching mice, and many breeds have been developed.", "A wild animal of the cat family.", "Used in names of catlike animals of other families, e.g., ring-tailed cat.", "(especially among jazz enthusiasts) a man.", "short for catalytic converter", "short for catamaran"], "transitive verb": ["Raise (an anchor) from the surface of the water to the cathead."], "abbreviation": ["Computer-assisted (or -aided) testing.", "Clear air turbulence."]}}
{"cattle": {"plural noun": ["Large ruminant animals with horns and cloven hoofs, domesticated for meat or milk, or as beasts of burden; cows.", "Similar animals of a group related to domestic cattle, including yak, bison, and buffalo."]}}
{"donkey": {"noun": ["A domesticated hoofed mammal of the horse family with long ears and a braying call, used as a beast of burden; an ass.", "A stupid or foolish person."]}}
{"dog": {"noun": ["A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, nonretractable claws, and a barking, howling, or whining voice.", "A wild animal of the dog family.", "The male of an animal of the dog family, or of some other mammals such as the otter.", "An unpleasant, contemptible, or wicked man.", "Used to refer to a person of a specified kind in a tone of playful reproof, commiseration, or congratulation.", "Used in various phrases to refer to someone who is abject or miserable, especially because they have been treated harshly.", "A woman regarded as unattractive.", "A thing of poor quality; a failure.", "A mechanical device for gripping.", "Feet."], "transitive verb": ["Follow (someone or their movements) closely and persistently.", "(of a problem) cause continual trouble for.", "Act lazily; fail to try one's hardest.", "Grip (something) with a mechanical device."]}}
{"goat": {"noun": ["A hardy domesticated ruminant animal that has backward curving horns and (in the male) a beard. It is kept for its milk and meat and is noted for its lively and frisky behavior.", "A wild mammal related to the goat, such as the ibex, markhor, and tur.", "The zodiacal sign Capricorn or the constellation Capricornus.", "A lecherous man.", "A scapegoat."], "abbreviation": ["(especially of a sports player) greatest of all time."]}}
{"horse": {"noun": ["A large plant-eating domesticated mammal with solid hoofs and a flowing mane and tail, used for riding, racing, and to carry and pull loads.", "An adult male horse; a stallion or gelding.", "A wild mammal of the horse family.", "Cavalry.", "A frame or structure on which something is mounted or supported, especially a sawhorse.", "A horizontal bar, rail, or rope in the rigging of a sailing ship for supporting something.", "A unit of horsepower.", "Heroin.", "An obstruction in a vein."], "transitive verb": ["Provide (a person or vehicle) with a horse or horses."]}}
{"rabbit": {"noun": ["A burrowing, gregarious, plant-eating mammal with long ears, long hind legs, and a short tail.", "The flesh of the rabbit as food.", "The fur of the rabbit.", "A hare.", "A runner who acts as pacesetter in the first laps of a race."], "intransitive verb": ["Hunt rabbits.", "Talk at length, especially about trivial matters.", "Move quickly; run away."]}}
{"pig": {"noun": ["An omnivorous domesticated hoofed mammal with sparse bristly hair and a flat snout for rooting in the soil, kept for its meat.", "A wild animal of the pig family.", "A young pig; a piglet.", "The flesh of a pig, especially a young one, as food.", "A greedy, dirty, or unpleasant person.", "A police officer.", "An oblong mass of iron or lead from a smelting furnace.", "A device which fits snugly inside an oil or gas pipeline and is sent through it to clean or test the inside, or to act as a barrier."], "verb": ["Gorge oneself with food.", "(of a sow) give birth to piglets; farrow.", "Operate a pig within an oil or gas pipeline."]}}
{"aardwolf": {"noun": ["A nocturnal black-striped African mammal of the hyena family, feeding mainly on termites."]}}
{"aardvark": {"noun": ["A nocturnal burrowing mammal with long ears, a tubular snout, and a long extensible tongue, feeding on ants and termites. Aardvarks are native to Africa and have no close relatives."]}}
{"alligator": {"noun": ["A large semiaquatic reptile similar to a crocodile but with a broader and shorter head, native to the Americas and China.", "The skin of the alligator or material resembling it."]}}
{"albatross": {"noun": ["A very large oceanic bird related to the shearwaters, with long narrow wings. Albatrosses, some species of which have wingspans greater than 10 feet (3.3 m), are found mainly in the southern oceans, with three kinds in the North Pacific.", "A source of frustration or guilt; an encumbrance (in allusion to Coleridge's The Rime of the Ancient Mariner)"]}}
{"alpaca": {"noun": ["A long-haired domesticated South American mammal related to the llama, valued for its wool.", "The wool of the alpaca.", "Fabric made from the wool of the alpaca, with or without other fibers."]}}
{"amphibian": {"noun": ["A cold-blooded vertebrate animal of a class that comprises the frogs, toads, newts, and salamanders. They are distinguished by having an aquatic gill-breathing larval stage followed (typically) by a terrestrial lung-breathing adult stage.", "A seaplane, tank, or other vehicle that can operate on land and on water."], "adjective": ["Relating to amphibians."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"anaconda": {"noun": ["A semiaquatic snake of the boa family that may grow to a great size, native to tropical South America."]}}
{"anglerfish": {"noun": ["A fish that lures prey with a fleshy lobe attached to a filament that arises from the snout and hangs in front of the mouth. Most anglerfishes have a very large head and wide mouth, with a small body and tail."]}}
{"angelfish": {"noun": ["Any of a number of laterally compressed deep-bodied fish with extended dorsal and anal fins, typically brightly colored or boldly striped."]}}
{"anteater": {"noun": ["A mammal that feeds on ants and termites. It has a long snout and sticky tongue."]}}
{"ant": {"noun": ["A small insect, often with a sting, that usually lives in a complex social colony with one or more breeding queens. It is wingless except for fertile adults, which often form large mating swarms, and is proverbial for industriousness."]}}
{"antelope": {"noun": ["A swift-running deerlike ruminant with smooth hair and upward-pointing horns, of a group native to Africa and Asia that includes the gazelles, impala, gnus, and elands."]}}
{"aphid": {"noun": ["A minute bug that feeds by sucking sap from plants. It reproduces rapidly, often producing live young without mating, and may live in large colonies that cause extensive damage to crops."]}}
{"ape": {"noun": ["A large primate that lacks a tail, including the gorilla, chimpanzees, orangutan, and gibbons.", "Used in names of macaque monkeys with short tails, e.g., Barbary ape.", "(in general use) any monkey.", "An unintelligent or clumsy person.", "An inferior imitator or mimic."], "transitive verb": ["Imitate the behavior or manner of (someone or something), especially in an absurd or unthinking way."]}}
{"armadillo": {"noun": ["A nocturnal omnivorous mammal that has large claws for digging and a body covered in bony plates. Armadillos are native to the south central US and Central and South America."]}}
{"asp": {"noun": ["A small southern European viper with an upturned snout."], "abbreviation": ["Application service provider, a company providing internet access to software applications that would otherwise have to be installed on individual computers."]}}
{"badger": {"noun": ["A heavily built omnivorous nocturnal mammal of the weasel family, typically having a gray and black coat.", "A native of Wisconsin."], "transitive verb": ["Repeatedly ask (someone) to do something; pester."]}}
{"baboon": {"noun": ["A large Old World ground-dwelling monkey with a long doglike snout, large teeth, and naked callosities on the buttocks. Baboons are social animals and live in troops.", "An ugly or uncouth person."]}}
{"bandicoot": {"noun": ["A mainly insectivorous marsupial native to Australia and New Guinea."]}}
{"barnacle": {"noun": ["A marine crustacean with an external shell, which attaches itself permanently to a variety of surfaces. Barnacles feed by filtering particles from the water using their modified feathery legs.", "Used figuratively to describe a tenacious person or thing."]}}
{"basilisk": {"noun": ["A mythical reptile with a lethal gaze or breath, hatched by a serpent from a cock's egg.", "A long, slender, and mainly bright green lizard found in Central America, the male of which has a crest running from the head to the tail. It can swim well, and is able to run on its hind legs across the surface of water."]}}
{"barracuda": {"noun": ["A large predatory tropical marine fish with a slender body and large jaws and teeth."]}}
{"bass": {"noun": ["The lowest adult male singing voice.", "Denoting the member of a family of instruments that is the lowest in pitch.", "A bass guitar or double bass.", "The low-frequency output of a radio or audio system, corresponding to the bass in music.", "The common European freshwater perch.", "Any of a number of fish similar to or related to the perch.", "another term for bast"]}}
{"bat": {"noun": ["An implement with a handle and a solid surface, usually of wood, used for hitting the ball in games such as baseball, cricket, and table tennis.", "The person batting, especially in cricket.", "Each of a pair of objects resembling table tennis bats, used by a person on the ground to guide a taxiing aircraft.", "A mainly nocturnal mammal capable of sustained flight, with membranous wings that extend between the fingers and connecting the forelimbs to the body and the hindlimbs to the tail.", "A woman regarded as unattractive or unpleasant."], "verb": ["(of a team or a player in sports such as baseball) take in turns the role of hitting rather than fielding.", "Hit at (someone or something) with the palm of one's hand."], "transitive verb": ["Flutter (one's eyelashes or eyelids), typically in a flirtatious manner."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"bear": {"transitive verb": ["Carry the weight of; support.", "Take responsibility for.", "Be able to accept or stand up to.", "Endure (an ordeal or difficulty)", "Manage to tolerate (a situation or experience)", "Strongly dislike.", "(of a person) carry (someone or something)", "(of a vehicle or boat) convey (passengers or cargo)", "Have or display as a visible mark or feature.", "Be called by (a name or title)", "Carry or conduct oneself in a particular manner.", "Give birth to (a child)", "(of a tree or plant) produce (fruit or flowers)", "Turn and proceed in a specified direction."], "noun": ["A large, heavy mammal that walks on the soles of its feet, having thick fur and a very short tail. Bears are related to the dog family but most species are omnivorous.", "A teddy bear.", "A nickname for Russia.", "The constellation Ursa Major or Ursa Minor.", "A large, heavy, cumbersome man.", "A gay or bisexual man with a burly physique and a large amount of body hair.", "A rough, bad-mannered, or uncouth person.", "Something that is very difficult or unpleasant to deal with.", "A person who forecasts that prices of stocks or commodities will fall, especially a person who sells shares hoping to buy them back later at a lower price."]}}
{"bedbug": {"noun": ["A bloodsucking bug which is a parasite of birds and mammals."]}}
{"beaver": {"noun": ["A large semiaquatic broad-tailed rodent that is native to North America and northern Eurasia. It is noted for its habit of gnawing through tree trunks to fell the trees in order to feed on the bark and build dams.", "The soft light brown fur of the beaver.", "A hat made of felted beaver fur.", "A heavy woolen cloth resembling felted beaver fur.", "A very hard-working person.", "The lower part of the face guard of a helmet in a suit of armor. The term is also used to refer to the upper part or visor, or to a single movable guard.", "A woman's genitals or pubic area.", "A woman."], "intransitive verb": ["Work hard."]}}
{"bee": {"noun": ["A honeybee.", "An insect of a large group to which the honeybee belongs, including many solitary as well as social kinds.", "A meeting for communal work or amusement."]}}
{"beetle": {"noun": ["An insect of an order distinguished by forewings typically modified into hard wing cases (elytra) that cover and protect the hind wings and abdomen.", "A tool with a heavy head and a handle, used for tasks such as ramming, crushing, and driving wedges; a maul.", "A machine used for heightening the luster of cloth by pressure from rollers."], "verb": ["Make one's way hurriedly or with short, quick steps."], "transitive verb": ["Ram, crush, or drive with a beetle.", "Finish (cloth) with a beetle."], "intransitive verb": ["(of a rock or a person's eyebrows) be prominent or overhanging."], "adjective": ["(of a person's eyebrows) shaggy and projecting."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"bird": {"noun": ["A warm-blooded egg-laying vertebrate distinguished by the possession of feathers, wings, and a beak and (typically) by being able to fly.", "A bird that is hunted for sport or used for food.", "An aircraft, spacecraft, satellite, or guided missile.", "A person of a specified kind or character.", "A young woman or a girlfriend."]}}
{"bison": {"noun": ["A humpbacked shaggy-haired wild ox native to North America and Europe."]}}
{"blackbird": {"noun": ["A European thrush with mainly black plumage.", "An American bird with a strong pointed bill. The male has black plumage that is iridescent or has patches of red or yellow."]}}
{"boa": {"noun": ["A constrictor snake which bears live young and may reach great size, native to America, Africa, Asia, and some Pacific islands.", "Any snake that is a constrictor.", "A long, thin decorative scarf or stole made of feathers or a similar material."]}}
{"boar": {"noun": ["A tusked Eurasian wild pig from which domestic pigs are descended.", "The flesh of the wild boar as food.", "An uncastrated domestic male pig.", "The full-grown male of certain other animals, especially a badger, guinea pig, or hedgehog."]}}
{"bobcat": {"noun": ["A small North American cat species with a barred and spotted coat and a short tail."]}}
{"bobolink": {"noun": ["A North American songbird of the American blackbird family, with a bill resembling that of a finch. The male has black, buff, and white plumage."]}}
{"bonobo": {"noun": ["A chimpanzee with a black face and black hair, found in the rainforests of the Democratic Republic of Congo (formerly Zaire)."]}}
{"booby": {"noun": ["A stupid or childish person.", "A large tropical seabird of the gannet family, with brown, black, or white plumage and brightly colored feet.", "A woman's breast."]}}
{"bug": {"noun": ["A small insect.", "A harmful microorganism, as a bacterium or virus.", "An illness caused by a harmful microorganism such as a bacterium or virus.", "An enthusiastic, almost obsessive, interest in something.", "An insect of a large order distinguished by having mouthparts that are modified for piercing and sucking.", "A miniature microphone, typically concealed in a room or telephone, used for surveillance.", "An error in a computer program or system."], "transitive verb": ["Conceal a miniature microphone in (a room or device) in order to monitor or record someone's conversations.", "Record or monitor (a conversation) by concealing a microphone in a room or telephone.", "Annoy or bother (someone)"]}}
{"bovid": {"noun": ["A mammal of the cattle family (Bovidae)."]}}
{"butterfly": {"noun": ["A nectar-feeding insect with two pairs of large, typically brightly colored wings that are covered with microscopic scales. Butterflies are distinguished from moths by having clubbed or dilated antennae, holding their wings erect when at rest, and being active by day.", "Having a two-lobed shape resembling the spread wings of a butterfly.", "A showy or frivolous person.", "A fluttering and nauseous sensation felt in the stomach when one is nervous.", "A stroke in swimming in which both arms are raised out of the water and lifted forwards together."], "transitive verb": ["Split (a piece of meat or fish) almost in two and spread it out flat."]}}
{"buzzard": {"noun": ["A large hawklike bird of prey with broad wings and a rounded tail, typically seen soaring in wide circles.", "A North American vulture, especially a turkey vulture."]}}
{"canid": {"noun": ["A mammal of the dog family (Canidae)."]}}
{"camel": {"noun": ["A large, long-necked ungulate mammal of arid country, with long slender legs, broad cushioned feet, and either one or two humps on the back. Camels can survive for long periods without food or drink, chiefly by using up the fat reserves in their humps.", "A fabric made from camel hair.", "A light yellowish-brown color like that of camel hair.", "An apparatus for raising a sunken ship, consisting of one or more watertight chests to provide buoyancy."]}}
{"capybara": {"noun": ["A South American mammal that resembles a giant long-legged guinea pig. It lives in groups near water and is the largest living rodent."]}}
{"cardinal": {"noun": ["A leading dignitary of the Roman Catholic Church. Cardinals are nominated by the Pope, and form the Sacred College which elects succeeding popes (now invariably from among their own number)", "A deep scarlet color like that of a cardinal's cassock.", "A New World songbird of the bunting family, with a stout bill and typically with a conspicuous crest. The male is partly or mostly red in color."], "adjective": ["Of the greatest importance; fundamental."]}}
{"caribou": {"noun": ["A large North American reindeer."]}}
{"carp": {"noun": ["A deep-bodied freshwater fish, typically with barbels around the mouth. Carp are farmed for food in some parts of the world and are widely kept in large ponds."], "intransitive verb": ["Complain or find fault continually about trivial matters."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"cat": {"noun": ["A small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws. It is widely kept as a pet or for catching mice, and many breeds have been developed.", "A wild animal of the cat family.", "Used in names of catlike animals of other families, e.g., ring-tailed cat.", "(especially among jazz enthusiasts) a man.", "short for catalytic converter", "short for catamaran"], "transitive verb": ["Raise (an anchor) from the surface of the water to the cathead."], "abbreviation": ["Computer-assisted (or -aided) testing.", "Clear air turbulence."]}}
{"caterpillar": {"noun": ["The larva of a butterfly or moth, having a segmented wormlike body with three pairs of true legs and several pairs of appendages similar to legs. Caterpillars may be hairy, have warning coloration, or be colored to resemble their surroundings.", "(in general use) any insect larva resembling the larvae of butterflies and moths, especially the sawfly.", "An articulated steel band passing around the wheels of a vehicle for travel on rough ground.", "A vehicle with caterpillar tracks."]}}
{"cattle": {"plural noun": ["Large ruminant animals with horns and cloven hoofs, domesticated for meat or milk, or as beasts of burden; cows.", "Similar animals of a group related to domestic cattle, including yak, bison, and buffalo."]}}
{"catfish": {"noun": ["A freshwater or marine fish with barbels resembling whiskers around the mouth, typically bottom-dwelling."], "verb": ["Fish for catfish.", "Lure (someone) into a relationship by means of a fictional online persona."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"centipede": {"noun": ["A predatory myriapod invertebrate with a flattened elongated body composed of many segments. Most segments bear a single pair of legs."]}}
{"cephalopod": {"noun": ["An active predatory mollusk of the large class Cephalopoda, such as an octopus or squid."]}}
{"chameleon": {"noun": ["A small slow-moving Old World lizard with a prehensile tail, long extensible tongue, protruding eyes that rotate independently, and a highly developed ability to change color.", "An anole (tree-dwelling lizard).", "A person who changes their opinions or behavior according to the situation."]}}
{"cheetah": {"noun": ["A large spotted cat found in Africa and parts of Asia. It is the fastest animal on land."]}}
{"chickadee": {"noun": ["A North American titmouse, in particular: the black-capped chickadee (Parus atricapillus), with distinctive black cap and throat, and the similar but smaller Carolina chickadee (P. carolinensis)."]}}
{"chicken": {"noun": ["A domestic fowl kept for its eggs or meat, especially a young one.", "Meat from a chicken.", "A cowardly person; a coward.", "A game in which the first person to lose nerve and withdraw from a dangerous situation is the loser."], "adjective": ["Cowardly."], "intransitive verb": ["Withdraw from or fail in something through lack of nerve."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"dinosaur": {"noun": ["A fossil reptile of the Mesozoic era, in many species reaching an enormous size.", "A person or thing that is outdated or has become obsolete because of failure to adapt to changing circumstances."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"dog": {"noun": ["A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, nonretractable claws, and a barking, howling, or whining voice.", "A wild animal of the dog family.", "The male of an animal of the dog family, or of some other mammals such as the otter.", "An unpleasant, contemptible, or wicked man.", "Used to refer to a person of a specified kind in a tone of playful reproof, commiseration, or congratulation.", "Used in various phrases to refer to someone who is abject or miserable, especially because they have been treated harshly.", "A woman regarded as unattractive.", "A thing of poor quality; a failure.", "A mechanical device for gripping.", "Feet."], "transitive verb": ["Follow (someone or their movements) closely and persistently.", "(of a problem) cause continual trouble for.", "Act lazily; fail to try one's hardest.", "Grip (something) with a mechanical device."]}}
{"donkey": {"noun": ["A domesticated hoofed mammal of the horse family with long ears and a braying call, used as a beast of burden; an ass.", "A stupid or foolish person."]}}
{"dolphin": {"noun": ["A small gregarious toothed whale that typically has a beaklike snout and a curved fin on the back. Dolphins have become well known for their sociable nature and high intelligence.", "A bollard, pile, or buoy for mooring boats.", "A structure for protecting the pier of a bridge."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"dormouse": {"noun": ["An agile mouse-like rodent with a hairy or bushy tail, found in Africa and Eurasia. Some kinds are noted for spending long periods in hibernation."]}}
{"dove": {"noun": ["A stocky seed- or fruit-eating bird with a small head, short legs, and a cooing voice. Doves are generally smaller and more delicate than pigeons, but many kinds have been given both names.", "A person who advocates peaceful or conciliatory policies, especially in foreign affairs.", "(in Christian art and poetry) the Holy Spirit (as represented in John 1:32)."]}}
{"dragonfly": {"noun": ["A fast-flying long-bodied predatory insect with two pairs of large transparent wings which are spread out sideways at rest. The voracious aquatic larvae take up to five years to reach adulthood."]}}
