{"cat": {"noun": ["A small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws. It is widely kept as a pet or for catching mice, and many breeds have been developed.", "A wild animal of the cat family.", "Used in names of catlike animals of other families, e.g., ring-tailed cat.", "(particularly among jazz enthusiasts) a person, especially a man.", "short for catalytic converter", "short for catalytic converter", "short for catamaran", "short for catamaran"], "transitive verb": ["Raise (an anchor) from the surface of the water to the cathead."], "abbreviation": ["Computer-assisted (or -aided) testing.", "Clear air turbulence."]}}
{"cattle": {"plural noun": ["Large ruminant animals with horns and cloven hoofs, domesticated for meat or milk, or as beasts of burden; cows.", "Similar animals of a group related to domestic cattle, including yak, bison, and buffalo."]}}
{"dog": {"noun": ["A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, nonretractable claws, and a barking, howling, or whining voice.", "A wild animal of the dog family.", "The male of an animal of the dog family, or of some other mammals such as the otter.", "A person regarded as unpleasant, contemptible, or wicked (used as a term of abuse)", "Used to refer to a person of a specified kind in a tone of playful reproof, commiseration, or congratulation.", "Used in various phrases to refer to someone who is abject or miserable, especially because they have been treated harshly.", "A woman regarded as unattractive.", "A thing of poor quality; a failure.", "A mechanical device for gripping.", "Feet."], "transitive verb": ["Follow (someone or their movements) closely and persistently.", "(of a problem) cause continual trouble for.", "Act lazily; fail to try one's hardest.", "Grip (something) with a mechanical device."]}}
{"donkey": {"noun": ["A domesticated hoofed mammal of the horse family with long ears and a braying call, used as a beast of burden; an ass.", "A stupid or foolish person."]}}
{"goat": {"noun": ["A hardy domesticated ruminant animal that has backward curving horns and (in the male) a beard. It is kept for its milk and meat and is noted for its lively and frisky behavior.", "A wild mammal related to the goat, such as the ibex, markhor, and tur.", "The zodiacal sign Capricorn or the constellation Capricornus.", "A lecherous man.", "A scapegoat."], "abbreviation": ["(especially of a sports player) greatest of all time."]}}
{"horse": {"noun": ["A large plant-eating domesticated mammal with solid hoofs and a flowing mane and tail, used for riding, racing, and to carry and pull loads.", "An adult male horse; a stallion or gelding.", "A wild mammal of the horse family.", "Cavalry.", "A frame or structure on which something is mounted or supported, especially a sawhorse.", "A horizontal bar, rail, or rope in the rigging of a sailing ship for supporting something.", "A unit of horsepower.", "Heroin.", "An obstruction in a vein."], "transitive verb": ["Provide (a person or vehicle) with a horse or horses."]}}
{"pig": {"noun": ["An omnivorous domesticated hoofed mammal with sparse bristly hair and a flat snout for rooting in the soil, kept for its meat.", "A wild animal of the pig family.", "A young pig; a piglet.", "The flesh of a pig, especially a young one, as food.", "A greedy, dirty, or unpleasant person.", "A police officer.", "An oblong mass of iron or lead from a smelting furnace.", "A device which fits snugly inside an oil or gas pipeline and is sent through it to clean or test the inside, or to act as a barrier."], "intransitive verb": ["Gorge oneself with food.", "Crowd together with other people in disorderly or dirty conditions.", "(of a sow) give birth to piglets; farrow.", "Operate a pig within an oil or gas pipeline."]}}
{"rabbit": {"noun": ["A burrowing, gregarious, plant-eating mammal with long ears, long hind legs, and a short tail.", "The flesh of the rabbit as food.", "The fur of the rabbit.", "A hare.", "A runner who acts as pacesetter in the first laps of a race."], "intransitive verb": ["Hunt rabbits.", "Talk at length, especially about trivial matters.", "Move quickly; run away."]}}
{"aardvark": {"noun": ["A nocturnal burrowing mammal with long ears, a tubular snout, and a long extensible tongue, feeding on ants and termites. Aardvarks are native to Africa and have no close relatives."]}}
{"aardwolf": {"noun": ["A nocturnal black-striped African mammal of the hyena family, feeding mainly on termites."]}}
{"albatross": {"noun": ["A very large oceanic bird related to the shearwaters, with long narrow wings. Albatrosses, some species of which have wingspans greater than 10 feet (3.3 m), are found mainly in the southern oceans, with three kinds in the North Pacific.", "A source of frustration or guilt; an encumbrance (in allusion to Coleridge's The Rime of the Ancient Mariner)"]}}
{"alligator": {"noun": ["A large semiaquatic reptile similar to a crocodile but with a broader and shorter head, native to the Americas and China.", "The skin of the alligator or material resembling it."]}}
{"amphibian": {"noun": ["A cold-blooded vertebrate animal of a class that comprises the frogs, toads, newts, and salamanders. They are distinguished by having an aquatic gill-breathing larval stage followed (typically) by a terrestrial lung-breathing adult stage.", "A seaplane, tank, or other vehicle that can operate on land and on water."], "adjective": ["Relating to amphibians."]}}
{"alpaca": {"noun": ["A long-haired domesticated South American mammal related to the llama, valued for its wool.", "The wool of the alpaca.", "Fabric made from the wool of the alpaca, with or without other fibers."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"anaconda": {"noun": ["A semiaquatic snake of the boa family that may grow to a great size, native to tropical South America."]}}
{"angelfish": {"noun": ["Any of a number of laterally compressed deep-bodied fish with extended dorsal and anal fins, typically brightly colored or boldly striped."]}}
{"anglerfish": {"noun": ["A fish that lures prey with a fleshy lobe attached to a filament that arises from the snout and hangs in front of the mouth. Most anglerfishes have a very large head and wide mouth, with a small body and tail."]}}
{"anteater": {"noun": ["A mammal that feeds on ants and termites. It has a long snout and sticky tongue."]}}
{"ant": {"noun": ["A small insect, often with a sting, that usually lives in a complex social colony with one or more breeding queens. It is wingless except for fertile adults, which often form large mating swarms, and is proverbial for industriousness."]}}
{"antelope": {"noun": ["A swift-running deerlike ruminant with smooth hair and upward-pointing horns, of a group native to Africa and Asia that includes the gazelles, impala, gnus, and elands."]}}
{"aphid": {"noun": ["A minute bug that feeds by sucking sap from plants. It reproduces rapidly, often producing live young without mating, and may live in large colonies that cause extensive damage to crops."]}}
{"ape": {"noun": ["A large primate that lacks a tail, including the gorilla, chimpanzees, orangutan, and gibbons.", "Used in names of macaque monkeys with short tails, e.g., Barbary ape.", "(in general use) any monkey.", "An unintelligent or clumsy person.", "An inferior imitator or mimic."], "transitive verb": ["Imitate the behavior or manner of (someone or something), especially in an absurd or unthinking way."]}}
{"asp": {"noun": ["A small southern European viper with an upturned snout."], "abbreviation": ["Application service provider, a company providing Internet access to software applications that would otherwise have to be installed on individual computers."]}}
{"armadillo": {"noun": ["A nocturnal omnivorous mammal that has large claws for digging and a body covered in bony plates. Armadillos are native to the south central US and Central and South America."]}}
{"baboon": {"noun": ["A large Old World ground-dwelling monkey with a long doglike snout, large teeth, and naked callosities on the buttocks. Baboons are social animals and live in troops.", "An ugly or uncouth person."]}}
{"badger": {"noun": ["A heavily built omnivorous nocturnal mammal of the weasel family, typically having a gray and black coat.", "A native of Wisconsin."], "transitive verb": ["Repeatedly ask (someone) to do something; pester."]}}
{"bandicoot": {"noun": ["A mainly insectivorous marsupial native to Australia and New Guinea."]}}
{"barnacle": {"noun": ["A marine crustacean with an external shell, which attaches itself permanently to a variety of surfaces. Barnacles feed by filtering particles from the water using their modified feathery legs.", "Used figuratively to describe a tenacious person or thing."]}}
{"barracuda": {"noun": ["A large predatory tropical marine fish with a slender body and large jaws and teeth."]}}
{"basilisk": {"noun": ["A mythical reptile with a lethal gaze or breath, hatched by a serpent from a cock's egg.", "A long, slender, and mainly bright green lizard found in Central America, the male of which has a crest running from the head to the tail. It can swim well, and is able to run on its hind legs across the surface of water."]}}
{"bat": {"noun": ["An implement with a handle and a solid surface, usually of wood, used for hitting the ball in games such as baseball, cricket, and table tennis.", "The person batting, especially in cricket.", "Each of a pair of objects resembling table tennis bats, used by a person on the ground to guide a taxiing aircraft.", "A mainly nocturnal mammal capable of sustained flight, with membranous wings that extend between the fingers and connecting the forelimbs to the body and the hindlimbs to the tail.", "A woman regarded as unattractive or unpleasant."], "verb": ["(of a team or a player in sports such as baseball) take in turns the role of hitting rather than fielding.", "Hit at (someone or something) with the palm of one's hand."], "transitive verb": ["Flutter (one's eyelashes or eyelids), typically in a flirtatious manner."]}}
{"bass": {"noun": ["The lowest adult male singing voice.", "Denoting the member of a family of instruments that is the lowest in pitch.", "A bass guitar or double bass.", "The low-frequency output of a radio or audio system, corresponding to the bass in music.", "The common European freshwater perch.", "Any of a number of fish similar to or related to the perch.", "another term for bast", "another term for bast"]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"bear": {"transitive verb": ["(of a person) carry.", "(of a vehicle or boat) convey (passengers or cargo)", "Have or display as a visible mark or feature.", "Be called by (a name or title)", "Carry or conduct oneself in a particular manner.", "Support.", "Take responsibility for.", "Be able to accept or stand up to.", "Endure (an ordeal or difficulty)", "Manage to tolerate (a situation or experience)", "Strongly dislike.", "Give birth to (a child)", "(of a tree or plant) produce (fruit or flowers)", "Turn and proceed in a specified direction."], "noun": ["A large, heavy mammal that walks on the soles of its feet, having thick fur and a very short tail. Bears are related to the dog family but most species are omnivorous.", "A teddy bear.", "A nickname for Russia.", "The constellation Ursa Major or Ursa Minor.", "A large, heavy, cumbersome man.", "A gay or bisexual man with a burly physique and a large amount of body hair.", "A rough, bad-mannered, or uncouth person.", "Something that is very difficult or unpleasant to deal with.", "A person who forecasts that prices of stocks or commodities will fall, especially a person who sells shares hoping to buy them back later at a lower price."]}}
{"beaver": {"noun": ["A large semiaquatic broad-tailed rodent that is native to North America and northern Eurasia. It is noted for its habit of gnawing through tree trunks to fell the trees in order to feed on the bark and build dams.", "The soft light brown fur of the beaver.", "A hat made of felted beaver fur.", "A heavy woolen cloth resembling felted beaver fur.", "A very hard-working person.", "The lower part of the face guard of a helmet in a suit of armor. The term is also used to refer to the upper part or visor, or to a single movable guard.", "A woman's genitals or pubic area.", "A woman."], "intransitive verb": ["Work hard."]}}
{"bedbug": {"noun": ["A bloodsucking bug which is a parasite of birds and mammals."]}}
{"beetle": {"noun": ["An insect of an order distinguished by forewings typically modified into hard wing cases (elytra) that cover and protect the hind wings and abdomen.", "A tool with a heavy head and a handle, used for tasks such as ramming, crushing, and driving wedges; a maul.", "A machine used for heightening the luster of cloth by pressure from rollers."], "verb": ["Make one's way hurriedly or with short, quick steps."], "transitive verb": ["Ram, crush, or drive with a beetle.", "Finish (cloth) with a beetle."], "intransitive verb": ["(of a rock or a person's eyebrows) be prominent or overhanging."], "adjective": ["(of a person's eyebrows) shaggy and projecting."]}}
{"bee": {"noun": ["A honeybee.", "An insect of a large group to which the honeybee belongs, including many solitary as well as social kinds.", "A meeting for communal work or amusement."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"bird": {"noun": ["A warm-blooded egg-laying vertebrate distinguished by the possession of feathers, wings, and a beak and (typically) by being able to fly.", "A bird that is hunted for sport or used for food.", "An aircraft, spacecraft, satellite, or guided missile.", "A person of a specified kind or character.", "A young woman or a girlfriend."]}}
{"blackbird": {"noun": ["A European thrush with mainly black plumage.", "An American bird with a strong pointed bill. The male has black plumage that is iridescent or has patches of red or yellow."]}}
{"bison": {"noun": ["A humpbacked shaggy-haired wild ox native to North America and Europe."]}}
{"boa": {"noun": ["A constrictor snake which bears live young and may reach great size, native to America, Africa, Asia, and some Pacific islands.", "Any snake that is a constrictor.", "A long, thin decorative scarf or stole made of feathers or a similar material."]}}
{"boar": {"noun": ["A tusked Eurasian wild pig from which domestic pigs are descended.", "The flesh of the wild boar as food.", "An uncastrated domestic male pig.", "The full-grown male of certain other animals, especially a badger, guinea pig, or hedgehog."]}}
{"bobolink": {"noun": ["A North American songbird of the American blackbird family, with a bill resembling that of a finch. The male has black, buff, and white plumage."]}}
{"bobcat": {"noun": ["A small North American cat species with a barred and spotted coat and a short tail."]}}
{"booby": {"noun": ["A stupid or childish person.", "A large tropical seabird of the gannet family, with brown, black, or white plumage and brightly colored feet.", "A woman's breast."]}}
{"bonobo": {"noun": ["A chimpanzee with a black face and black hair, found in the rainforests of the Democratic Republic of Congo (formerly Zaire)."]}}
{"bovid": {"noun": ["A mammal of the cattle family (Bovidae)."]}}
{"bug": {"noun": ["A small insect.", "A harmful microorganism, as a bacterium or virus.", "An illness caused by a harmful microorganism such as a bacterium or virus.", "An enthusiastic, almost obsessive, interest in something.", "An insect of a large order distinguished by having mouthparts that are modified for piercing and sucking.", "A miniature microphone, typically concealed in a room or telephone, used for surveillance.", "An error in a computer program or system."], "transitive verb": ["Conceal a miniature microphone in (a room or telephone) in order to monitor or record someone's conversations.", "Record or monitor (a conversation) by concealing a microphone in a room or telephone.", "Annoy or bother (someone)"]}}
{"butterfly": {"noun": ["A nectar-feeding insect with two pairs of large, typically brightly colored wings that are covered with microscopic scales. Butterflies are distinguished from moths by having clubbed or dilated antennae, holding their wings erect when at rest, and being active by day.", "Having a two-lobed shape resembling the spread wings of a butterfly.", "A showy or frivolous person.", "A fluttering and nauseous sensation felt in the stomach when one is nervous.", "A stroke in swimming in which both arms are raised out of the water and lifted forwards together."], "transitive verb": ["Split (a piece of meat or fish) almost in two and spread it out flat."]}}
{"buzzard": {"noun": ["A large hawklike bird of prey with broad wings and a rounded tail, typically seen soaring in wide circles.", "A North American vulture, especially a turkey vulture."]}}
{"canid": {"noun": ["A mammal of the dog family (Canidae)."]}}
{"camel": {"noun": ["A large, long-necked ungulate mammal of arid country, with long slender legs, broad cushioned feet, and either one or two humps on the back. Camels can survive for long periods without food or drink, chiefly by using up the fat reserves in their humps.", "A fabric made from camel hair.", "A light yellowish-brown color like that of camel hair.", "An apparatus for raising a sunken ship, consisting of one or more watertight chests to provide buoyancy."]}}
{"cardinal": {"noun": ["A leading dignitary of the Roman Catholic Church. Cardinals are nominated by the Pope, and form the Sacred College which elects succeeding popes (now invariably from among their own number)", "A deep scarlet color like that of a cardinal's cassock.", "A New World songbird of the bunting family, with a stout bill and typically with a conspicuous crest. The male is partly or mostly red in color."], "adjective": ["Of the greatest importance; fundamental."]}}
{"capybara": {"noun": ["A South American mammal that resembles a giant long-legged guinea pig. It lives in groups near water and is the largest living rodent."]}}
{"caribou": {"noun": ["A large North American reindeer."]}}
{"carp": {"noun": ["A deep-bodied freshwater fish, typically with barbels around the mouth. Carp are farmed for food in some parts of the world and are widely kept in large ponds."], "intransitive verb": ["Complain or find fault continually about trivial matters."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"cat": {"noun": ["A small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws. It is widely kept as a pet or for catching mice, and many breeds have been developed.", "A wild animal of the cat family.", "Used in names of catlike animals of other families, e.g., ring-tailed cat.", "(particularly among jazz enthusiasts) a person, especially a man.", "short for catalytic converter", "short for catalytic converter", "short for catamaran", "short for catamaran"], "transitive verb": ["Raise (an anchor) from the surface of the water to the cathead."], "abbreviation": ["Computer-assisted (or -aided) testing.", "Clear air turbulence."]}}
{"caterpillar": {"noun": ["The larva of a butterfly or moth, having a segmented wormlike body with three pairs of true legs and several pairs of appendages similar to legs. Caterpillars may be hairy, have warning coloration, or be colored to resemble their surroundings.", "(in general use) any insect larva resembling the larvae of butterflies and moths, especially the sawfly.", "An articulated steel band passing around the wheels of a vehicle for travel on rough ground.", "A vehicle with caterpillar tracks."]}}
{"cattle": {"plural noun": ["Large ruminant animals with horns and cloven hoofs, domesticated for meat or milk, or as beasts of burden; cows.", "Similar animals of a group related to domestic cattle, including yak, bison, and buffalo."]}}
{"catfish": {"noun": ["A freshwater or marine fish with barbels resembling whiskers around the mouth, typically bottom-dwelling."], "verb": ["Fish for catfish.", "Lure (someone) into a relationship by means of a fictional online persona."]}}
{"centipede": {"noun": ["A predatory myriapod invertebrate with a flattened elongated body composed of many segments. Most segments bear a single pair of legs."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"cephalopod": {"noun": ["An active predatory mollusk of the large class Cephalopoda, such as an octopus or squid."]}}
{"chameleon": {"noun": ["A small slow-moving Old World lizard with a prehensile tail, long extensible tongue, protruding eyes that rotate independently, and a highly developed ability to change color.", "An anole (tree-dwelling lizard).", "A person who changes their opinions or behavior according to the situation."]}}
{"cheetah": {"noun": ["A large spotted cat found in Africa and parts of Asia. It is the fastest animal on land."]}}
{"chickadee": {"noun": ["A North American titmouse, in particular: the black-capped chickadee (Parus atricapillus), with distinctive black cap and throat, and the similar but smaller Carolina chickadee (P. carolinensis)."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"chicken": {"noun": ["A domestic fowl kept for its eggs or meat, especially a young one.", "Meat from a chicken.", "A coward.", "A game in which the first person to lose nerve and withdraw from a dangerous situation is the loser."], "adjective": ["Cowardly."], "intransitive verb": ["Withdraw from or fail in something through lack of nerve."]}}
{"chinchilla": {"noun": ["A small South American rodent with soft gray fur and a long bushy tail.", "A cat or rabbit of a breed with silver-gray or gray fur.", "The highly valued fur of the chinchilla, or of the chinchilla rabbit."]}}
{"chimpanzee": {"noun": ["A great ape with large ears, mainly black coloration, and lighter skin on the face, native to the forests of western and central Africa. Chimpanzees show advanced behavior such as the making and using of tools."]}}
{"chipmunk": {"noun": ["A burrowing ground squirrel with cheek pouches and light and dark stripes running down the body, found in North America and northern Eurasia."]}}
{"clam": {"noun": ["A marine bivalve mollusk with shells of equal size.", "Any of a number of edible bivalve mollusks, e.g. a scallop.", "A dollar.", "A shy or withdrawn person."], "intransitive verb": ["Dig for or collect clams.", "Abruptly stop talking, either for fear of revealing a secret or from shyness."]}}
{"clownfish": {"noun": ["A small tropical marine fish with bold vertical stripes or other bright coloration. It lives in close association with anemones and is protected from their stings by mucus."]}}
{"cobra": {"noun": ["A highly venomous snake native to Africa and Asia that spreads the skin of its neck into a hood when disturbed.", "A yoga pose assumed by lying on one's stomach and raising one's upper body so as to curve it backwards, using one's arms and hands for support.", "(in the UK) a government committee, typically chaired by the prime minister or a senior minister, that is specially convened as a result of a major emergency in order to coordinate the response of the various government departments and agencies responsible for handling the situation."]}}
{"cockroach": {"noun": ["A scavenging insect that resembles a beetle, having long antennae and legs and typically a broad, flattened body. Several tropical kinds have become established worldwide as household pests."]}}
{"cod": {"noun": ["A large marine fish with a small barbel on the chin.", "Used in names of fishes similar or related to the cod, e.g., rock cod, tomcod.", "A joke or hoax.", "A foolish person.", "Nonsense."], "adjective": ["Not authentic; fake."], "transitive verb": ["Play a joke or trick on (someone)"], "abbreviation": ["Cash on delivery.", "Collect on delivery."]}}
{"condor": {"noun": ["A large New World vulture with a bare head and mainly black plumage, living in mountainous country and spending much time soaring."]}}
{"constrictor": {"noun": ["A snake that kills by coiling around its prey and asphyxiating it.", "A muscle whose contraction narrows a vessel or passage.", "Each of the muscles which constrict the pharynx."]}}
{"coral": {"noun": ["A hard stony substance secreted by certain marine coelenterates as an external skeleton, typically forming large reefs in warm seas.", "Precious red coral, used in jewelry.", "The pinkish-red color of red coral.", "A sedentary coelenterate of warm and tropical seas, with a calcareous, horny, or soft skeleton. Most corals are colonial and many rely on the presence of green algae in their tissues to obtain energy from sunlight.", "The unfertilized roe of a lobster or scallop, which is used as food and becomes reddish when cooked."]}}
{"cougar": {"noun": ["A large American wild cat with a plain tawny to grayish coat, found from Canada to Patagonia.", "An older woman seeking a sexual relationship with a younger man."]}}
{"cow": {"noun": ["A fully grown female animal of a domesticated breed of ox, kept to produce milk or beef.", "(loosely) a domestic bovine animal, regardless of sex or age.", "(in farming) a female domestic bovine animal which has borne more than one calf.", "The female of certain other large animals, for example elephant, rhinoceros, whale, or seal.", "An unpleasant or disliked woman.", "An unpleasant person or thing."], "transitive verb": ["Cause (someone) to submit to one's wishes by intimidation."]}}
{"coyote": {"noun": ["A wild dog that resembles the wolf, native to North America.", "A person who smuggles Latin Americans across the US border, typically for a high fee."]}}
{"crab": {"noun": ["A crustacean with a broad carapace, stalked eyes, and five pairs of legs, the first pair of which are modified as pincers. Crabs are abundant on many shores, especially in the tropics, where some have become adapted to life on land.", "The flesh of a crab as food.", "The zodiacal sign or constellation Cancer.", "A louse that infests human body hair, especially in the genital region, causing extreme irritation.", "An infestation of crab lice.", "A machine for picking up and lifting heavy weights.", "short for crab apple", "An irritable person."], "verb": ["Move sideways or obliquely.", "Steer (an aircraft or ship) slightly sideways to compensate for a crosswind or current.", "Fish for crabs.", "Grumble, typically about something petty.", "Act so as to spoil."]}}
{"crane": {"noun": ["A large, tall machine used for moving heavy objects by suspending them from a projecting arm or beam.", "A moving platform supporting a television or movie camera.", "A tall, long-legged, long-necked bird, typically with white or gray plumage and often with tail plumes and patches of bare red skin on the head. Cranes are noted for their elaborate courtship dances."], "verb": ["Stretch out one's body or neck in order to see something.", "Stretch out (one's neck) so as to see something.", "Move (a heavy object) with a crane."]}}
{"crayfish": {"noun": ["A nocturnal freshwater crustacean that resembles a small lobster and inhabits streams and rivers."]}}
{"crawdad": {"noun": ["A freshwater crayfish."]}}
{"crocodile": {"noun": ["A large predatory semiaquatic reptile with long jaws, long tail, short legs, and a horny textured skin, using submersion and stealth to approach prey unseen. The crocodile has been extensively hunted for its valuable skin.", "Leather made from crocodile skin, used especially to make bags and shoes.", "A line of schoolchildren walking in pairs."]}}
{"cricket": {"noun": ["An insect related to the grasshoppers. The male produces a characteristic rhythmical chirping sound.", "An open-air game played on a large grass field with ball, bats, and two wickets, between teams of eleven players, the object of the game being to score more runs than the opposition.", "A low wooden stool; a footstool."]}}
{"cuckoo": {"noun": ["A medium-sized long-tailed bird, typically with a gray or brown back and barred or pale underparts. Many cuckoos lay their eggs in the nests of small songbirds.", "A mad person."], "adjective": ["Mad; crazy."]}}
{"crow": {"noun": ["A large perching bird with mostly glossy black plumage, a heavy bill, and a raucous voice.", "A woman, especially an old or ugly one.", "The constellation Corvus.", "The cry of a rooster.", "A sound made by a person expressing triumph or happiness.", "A member of a North American people inhabiting eastern Montana.", "The Siouan language of the Crow."], "intransitive verb": ["(of a rooster) utter its characteristic loud cry.", "(of a person) make a sound expressing a feeling of happiness or triumph.", "Say something in a tone of gloating satisfaction."], "adjective": ["Relating to the Crow or their language."]}}
{"cicada": {"noun": ["A large homopterous insect with long transparent wings, occurring chiefly in warm countries. The male cicada makes a loud shrill droning noise by vibrating two membranes on its abdomen."]}}
{"damselfly": {"noun": ["A slender insect related to the dragonflies, having weak flight and typically resting with the wings folded back along the body."]}}
{"deer": {"noun": ["A hoofed grazing or browsing animal, with branched bony antlers that are shed annually and typically borne only by the male."]}}
{"dingo": {"noun": ["A wild or half-domesticated dog with a sandy-colored coat, found in Australia."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"dinosaur": {"noun": ["A fossil reptile of the Mesozoic era, in many species reaching an enormous size.", "A person or thing that is outdated or has become obsolete because of failure to adapt to changing circumstances."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"dog": {"noun": ["A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, nonretractable claws, and a barking, howling, or whining voice.", "A wild animal of the dog family.", "The male of an animal of the dog family, or of some other mammals such as the otter.", "A person regarded as unpleasant, contemptible, or wicked (used as a term of abuse)", "Used to refer to a person of a specified kind in a tone of playful reproof, commiseration, or congratulation.", "Used in various phrases to refer to someone who is abject or miserable, especially because they have been treated harshly.", "A woman regarded as unattractive.", "A thing of poor quality; a failure.", "A mechanical device for gripping.", "Feet."], "transitive verb": ["Follow (someone or their movements) closely and persistently.", "(of a problem) cause continual trouble for.", "Act lazily; fail to try one's hardest.", "Grip (something) with a mechanical device."]}}
{"dolphin": {"noun": ["A small gregarious toothed whale that typically has a beaklike snout and a curved fin on the back. Dolphins have become well known for their sociable nature and high intelligence.", "A bollard, pile, or buoy for mooring boats.", "A structure for protecting the pier of a bridge."]}}
{"donkey": {"noun": ["A domesticated hoofed mammal of the horse family with long ears and a braying call, used as a beast of burden; an ass.", "A stupid or foolish person."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"dormouse": {"noun": ["An agile mouse-like rodent with a hairy or bushy tail, found in Africa and Eurasia. Some kinds are noted for spending long periods in hibernation."]}}
{"dove": {"noun": ["A stocky seed- or fruit-eating bird with a small head, short legs, and a cooing voice. Doves are generally smaller and more delicate than pigeons, but many kinds have been given both names.", "A person who advocates peaceful or conciliatory policies, especially in foreign affairs.", "(in Christian art and poetry) the Holy Spirit (as represented in John 1:32)."]}}
{"dragonfly": {"noun": ["A fast-flying long-bodied predatory insect with two pairs of large transparent wings which are spread out sideways at rest. The voracious aquatic larvae take up to five years to reach adulthood."]}}
{"duck": {"noun": ["A waterbird with a broad blunt bill, short legs, webbed feet, and a waddling gait.", "A female duck.", "The meat of a duck as food.", "A pure white thin-shelled bivalve mollusk found off the Atlantic coasts of America.", "An amphibious transport vehicle.", "A quick lowering of the head.", "Dear; darling (used as an informal or affectionate form of address, especially among cockneys)", "A strong linen or cotton fabric, used chiefly for casual or work clothes and sails.", "Pants made of duck fabric.", "A batsman's score of zero."], "verb": ["Lower the head or the body quickly to avoid a blow or so as not to be seen.", "Depart quickly.", "Avoid (a blow) by moving down quickly.", "Evade or avoid (an unwelcome duty or undertaking)", "Plunge one's head or body underwater briefly.", "Refrain from playing a winning card on a particular trick for tactical reasons."]}}
{"dragon": {"noun": ["A mythical monster like a giant reptile. In European tradition the dragon is typically fire-breathing and tends to symbolize chaos or evil, whereas in East Asia it is usually a beneficent symbol of fertility, associated with water and the heavens.", "A fierce and intimidating person, especially a woman.", "(in the 16th and 17th centuries) a short musket carried on the belt of a soldier, especially a mounted infantryman.", "A soldier armed with a short musket carried on the belt."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"eagle": {"noun": ["A large bird of prey with a massive hooked bill and long broad wings, renowned for its keen sight and powerful soaring flight.", "A figure of an eagle, especially as a symbol of the US, or formerly as a Roman or French ensign.", "A score of two strokes under par at a hole.", "In the US, a former gold coin worth ten dollars."], "transitive verb": ["Play (a hole) in two strokes under par."]}}
{"earthworm": {"noun": ["A burrowing annelid worm that lives in the soil. Earthworms play an important role in aerating and draining the soil and in burying organic matter."]}}
{"earwig": {"noun": ["A small elongated insect with a pair of terminal appendages that resemble pincers. The females typically care for their eggs and young until they are grown."], "intransitive verb": ["Secretly listen to a conversation.", "Influence (someone) by secret means."]}}
{"lion": {"noun": ["A large tawny-colored cat that lives in prides, found in Africa and northwestern India. The male has a flowing shaggy mane and takes little part in hunting, which is done cooperatively by the females.", "The lion as an emblem (e.g. of English or Scottish royalty) or as a charge in heraldry.", "The zodiacal sign or constellation Leo.", "A brave or strong person.", "An influential or celebrated person.", "A member of a Lions Club."]}}
{"lizard": {"noun": ["A reptile that typically has a long body and tail, four legs, movable eyelids, and a rough, scaly, or spiny skin."], "proper noun": ["A promontory in southwestern England, in Cornwall. Its southern tip, Lizard Point, is the southernmost point of the British mainland."]}}
{"llama": {"noun": ["A domesticated pack animal of the camel family found in the Andes, valued for its soft woolly fleece.", "The wool of the llama.", "Cloth made from the wool of the llama."]}}
{"lobster": {"noun": ["A large marine crustacean with a cylindrical body, stalked eyes, and the first of its five pairs of limbs modified as pincers.", "The flesh of the lobster as food.", "Any of various crustaceans similar to the lobster, especially certain crayfish whose claws are eaten as food.", "A deep red color typical of a cooked lobster."], "intransitive verb": ["Catch lobsters."]}}
{"locust": {"noun": ["A large and mainly tropical grasshopper with strong powers of flight. It is usually solitary, but from time to time there is a population explosion, and it migrates in vast swarms that cause extensive damage to crops.", "The periodical cicada.", "The large edible pod of some plants of the pea family, in particular the carob bean, which is said to resemble a locust.", "Any of a number of pod-bearing trees of the pea family, in particular the carob tree and the black locust."]}}
{"loon": {"noun": ["A silly or foolish person.", "A large diving waterbird with a sleek black or gray head, a straight pointed bill, and short legs set far back under the body. Loons breed by lakes in northern latitudes and have wailing calls."], "verb": ["Act in a foolish or desultory way."]}}
{"louse": {"noun": ["Either of two small wingless parasitic insects that live on the skin of mammals and birds.", "Used in names of small invertebrates that parasitize aquatic animals or infest plants, e.g. fish louse.", "A contemptible or unpleasant person."], "transitive verb": ["Spoil or ruin something.", "Remove lice from."]}}
{"lungfish": {"noun": ["An elongated freshwater fish with one or two sacs which function as lungs, enabling it to breathe air. It lives in poorly oxygenated water and can estivate in mud for long periods to survive drought."]}}
{"lynx": {"noun": ["A wild cat with yellowish-brown fur (sometimes spotted), a short tail, and tufted ears, found chiefly in the northern latitudes of North America and Eurasia.", "The fur of the lynx."], "proper noun": ["An inconspicuous northern constellation (the Lynx), between Ursa Major and Gemini."], "adjective": ["Used with preceding Greek letter or numeral to designate a star in the Lynx constellation."]}}
{"macaw": {"noun": ["A large long-tailed parrot with brightly colored plumage, native to Central and South America."]}}
{"magpie": {"noun": ["A long-tailed crow with boldly marked (or green) plumage and a raucous voice.", "Used in similes or comparisons to refer to a person who collects things, especially things of little use or value, or a person who chatters idly."]}}
{"mackerel": {"noun": ["A migratory surface-dwelling predatory fish, commercially important as a food fish."]}}
{"mammal": {"noun": ["A warm-blooded vertebrate animal of a class that is distinguished by the possession of hair or fur, the secretion of milk by females for the nourishment of the young, and (typically) the birth of live young."]}}
{"manatee": {"noun": ["An aquatic mammal with a rounded tail flipper, living in shallow coastal waters and adjacent rivers of the tropical Atlantic."]}}
{"mandrill": {"noun": ["A large West African baboon with a brightly colored red and blue face, the male having a blue rump."]}}
{"marlin": {"noun": ["A large edible billfish of warm seas that is a highly prized game fish and typically reaches a great weight."]}}
{"marmot": {"noun": ["A heavily built, gregarious, burrowing rodent of both Eurasia and North America, typically living in mountainous country."]}}
{"marmoset": {"noun": ["A small Central and South American monkey with a silky coat and a long nonprehensile tail."]}}
{"marten": {"noun": ["A chiefly arboreal weasel-like mammal found in Eurasia and North America, hunted for its fur in many northern countries."]}}
{"marsupial": {"noun": ["A mammal of an order whose members are born incompletely developed and are typically carried and suckled in a pouch on the mother's belly. Marsupials are found mainly in Australia and New Guinea, although three families, including the opossums, live in America."], "adjective": ["Relating to the marsupials."]}}
{"mastodon": {"noun": ["A large extinct elephant-like mammal of the Miocene to Pleistocene epochs, having teeth of a relatively primitive form and number."]}}
{"meadowlark": {"noun": ["A ground-dwelling songbird of the American blackbird family, with a brown streaky back and yellow and black underparts."]}}
{"mink": {"noun": ["A small semiaquatic carnivore resembling the stoat, native to North America and Eurasia. The American mink is widely farmed for its fur, resulting in it becoming naturalized in many parts of Europe.", "The thick brown fur of the mink.", "A coat made of mink."]}}
{"meerkat": {"noun": ["A small southern African mongoose, especially the suricate."]}}
{"minnow": {"noun": ["A small freshwater Eurasian cyprinoid fish that typically forms large shoals.", "Any fish of the family Cyprinidae, the largest family of fishes, which includes carps, shiners, spinefins, squawfishes, chubs, daces, and stonerollers.", "Used in names of similar small freshwater fishes, e.g., mudminnow, topminnow.", "An artificial lure imitating a minnow.", "A person or organization of relatively small size, power, or influence."]}}
{"mite": {"noun": ["A minute arachnid which has four pairs of legs when adult, related to the ticks. Many kinds live in the soil and a number are parasitic on plants or animals.", "A small child or animal, especially when regarded as an object of sympathy.", "A very small amount.", "A small coin, in particular a small Flemish copper coin of very low face value."], "adverb": ["A little; slightly."]}}
{"mockingbird": {"noun": ["A long-tailed songbird with grayish plumage, found mainly in tropical America and noted for its mimicry of the calls and songs of other birds."]}}
{"mole": {"noun": ["A small burrowing insectivorous mammal with dark velvety fur, a long muzzle, and very small eyes.", "A spy who achieves over a long period an important position within the security defenses of a country.", "Someone within an organization who anonymously betrays confidential information.", "A small, often slightly raised blemish on the skin made dark by a high concentration of melanin.", "A large solid structure on a shore serving as a pier, breakwater, or causeway.", "A harbor formed or protected by a mole.", "The SI base unit for the amount of substance.", "An abnormal mass of tissue in the uterus.", "A highly spiced Mexican sauce made chiefly from chili peppers and chocolate, served with meat."]}}
{"mollusk": {"noun": ["An invertebrate of a large phylum which includes snails, slugs, mussels, and octopuses. They have a soft unsegmented body and live in aquatic or damp habitats, and most kinds have an external calcareous shell."]}}
{"mongoose": {"noun": ["A small carnivorous mammal with a long body and tail and a grizzled or banded coat, native to Africa and Asia."]}}
{"moose": {"noun": ["A large deer with palmate antlers, a sloping back, and a growth of skin hanging from the neck. It is native to northern Eurasia and northern North America."]}}
{"monkey": {"noun": ["A small to medium-sized primate that typically has a long tail, most kinds of which live in trees in tropical countries.", "(in general use) any primate.", "A mischievous person, especially a child.", "A person who is dominated or controlled by another (with reference to the monkey traditionally kept by an organ grinder).", "A pile-driving machine consisting of a heavy hammer or ram working vertically in a groove."], "intransitive verb": ["Behave in a silly or playful way.", "Tamper with.", "Ape; mimic."]}}
{"mosquito": {"noun": ["A slender long-legged fly with aquatic larvae. The bite of the bloodsucking female can transmit a number of serious diseases including malaria and encephalitis."]}}
{"moth": {"noun": ["A chiefly nocturnal insect related to the butterflies. It lacks the clubbed antennae of butterflies and typically has a stout body, drab coloration, and wings that fold flat when resting.", "A clothes moth."]}}
{"mouse": {"noun": ["A small rodent that typically has a pointed snout, relatively large ears and eyes, and a long tail.", "(in general use) any small mammal similar to a mouse, such as a shrew or vole.", "A shy, timid, and quiet person.", "A dull light brown color reminiscent of a mouse's fur.", "A small handheld device that is dragged across a flat surface to move the cursor on a computer screen, typically having buttons that are pressed to control functions.", "A lump or bruise, especially one on or near the eye."], "intransitive verb": ["(of a cat or owl) hunt for or catch mice.", "Prowl around as if searching.", "Use a mouse to move a cursor on a computer screen."]}}
{"mule": {"noun": ["The offspring of a donkey and a horse (strictly, a male donkey and a female horse), typically sterile and used as a beast of burden.", "A person compared to a mule, especially in being stubborn or obstinate.", "A courier for illegal drugs.", "A hybrid plant or animal, especially a sterile one.", "Any of several standard crossbred varieties of sheep.", "A kind of spinning machine producing yarn on spindles, invented by Samuel Crompton (1753–1827) in 1779.", "A small tractor or locomotive, typically one that is electrically powered.", "A coin with the obverse and reverse of designs not originally intended to be used together.", "A slipper or light shoe without a back."]}}
{"muskox": {"noun": ["A large heavily built goat-antelope with a thick shaggy coat and large curved horns, native to the tundra of North America and Greenland."]}}
{"narwhal": {"noun": ["A small Arctic whale, the male of which has a long forward-pointing spirally twisted tusk developed from one of its teeth."]}}
{"nightingale": {"noun": ["A small European thrush with drab brownish plumage, noted for the rich melodious song of the male, heard especially at night in breeding season."]}}
{"newt": {"noun": ["A small slender-bodied amphibian with lungs and a well-developed tail, typically spending its adult life on land and returning to water to breed."]}}
{"octopus": {"noun": ["A cephalopod mollusc with eight sucker-bearing arms, a soft body, strong beaklike jaws, and no internal shell."]}}
{"ocelot": {"noun": ["A medium-sized wild cat that has a tawny yellow coat marked with black blotches and spots, and ranges from southern Texas through South America.", "The fur of the ocelot."]}}
{"orangutan": {"noun": ["A large mainly solitary arboreal ape with long reddish hair, long arms, and hooked hands and feet, native to Borneo and Sumatra. The mature male develops fleshy cheek pads and a throat pouch."]}}
{"opossum": {"noun": ["An American marsupial which has a naked prehensile tail and hind feet with an opposable thumb."]}}
{"orca": {"noun": ["A large toothed whale with distinctive black-and-white markings and a prominent dorsal fin. It lives in groups that cooperatively hunt fish, seals, and penguins."]}}
{"ostrich": {"noun": ["A flightless swift-running African bird with a long neck, long legs, and two toes on each foot. It is the largest living bird, with males reaching an average height of 8 feet (2.5 m).", "A person who refuses to face reality or accept facts."]}}
{"otter": {"noun": ["A semiaquatic fish-eating mammal of the weasel family, with an elongated body, dense fur, and webbed feet."]}}
{"owl": {"noun": ["A nocturnal bird of prey with large forward-facing eyes surrounded by facial disks, a hooked beak, and typically a loud call."]}}
{"ox": {"noun": ["A castrated bull used as a draft animal.", "Any domesticated bovine animal kept for milk or meat; a cow or bull.", "Used in names of wild animals related to or resembling a domesticated ox, e.g. musk ox."]}}
{"panda": {"noun": ["A large bearlike mammal with characteristic black and white markings, native to certain mountain forests in China. It feeds almost entirely on bamboo and has become increasingly rare.", "A Brahmin expert in genealogy, who provides religious guidance and acts as a family priest."]}}
{"parakeet": {"noun": ["A small parrot with predominantly green plumage and a long tail."]}}
{"panther": {"noun": ["A leopard, especially a black one.", "A large American wild cat with a plain tawny to grayish coat, found from Canada to Patagonia."]}}
{"parrotfish": {"noun": ["Any of a number of brightly colored marine fish with a parrot-like beak, which they use to scrape food from coral and other hard surfaces.", "A brightly colored marine fish, especially one of the wrasse family."]}}
{"parrot": {"noun": ["A bird, often vividly colored, with a short down-curved hooked bill, grasping feet, and a raucous voice, found especially in the tropics and feeding on fruits and seeds. Many are popular as cage birds, and some are able to mimic the human voice."], "transitive verb": ["Repeat mechanically."]}}
{"partridge": {"noun": ["A short-tailed game bird with mainly brown plumage, native to Eurasia."]}}
{"peacock": {"noun": ["A male peafowl, which has very long tail feathers that have eye-like markings and can be erected and fanned out in display.", "An ostentatious or vain person."], "intransitive verb": ["Display oneself ostentatiously."]}}
{"peafowl": {"noun": ["A large crested pheasant native to Asia."]}}
{"pelican": {"noun": ["A large gregarious waterbird with a long bill, an extensible throat pouch for scooping up fish, and mainly white or gray plumage.", "A heraldic or artistic representation of a pelican, typically depicted pecking its own breast as a symbol of Christ."]}}
{"perch": {"noun": ["A thing on which a bird alights or roosts, typically a branch or a horizontal rod or bar in a birdcage.", "A place where someone or something rests or sits, especially a place that is high or precarious.", "An edible freshwater fish with a high spiny dorsal fin, dark vertical bars on the body, and orange lower fins.", "Used in names of other freshwater and marine fishes resembling or related to this, e.g., climbing perch, sea perch, surfperch.", "A linear or square rod."], "verb": ["(of a bird) alight or rest on something.", "(of a person) sit somewhere, especially on something high or narrow.", "(of a building) be situated above or on the edge of something.", "Set or balance someone or something on (something)"]}}
{"penguin": {"noun": ["A large flightless seabird of the southern hemisphere, with black upper parts and white underparts and wings developed into flippers for swimming under water."]}}
{"pheasant": {"noun": ["A large long-tailed game bird native to Asia, the male of which typically has very showy plumage."]}}
{"pig": {"noun": ["An omnivorous domesticated hoofed mammal with sparse bristly hair and a flat snout for rooting in the soil, kept for its meat.", "A wild animal of the pig family.", "A young pig; a piglet.", "The flesh of a pig, especially a young one, as food.", "A greedy, dirty, or unpleasant person.", "A police officer.", "An oblong mass of iron or lead from a smelting furnace.", "A device which fits snugly inside an oil or gas pipeline and is sent through it to clean or test the inside, or to act as a barrier."], "intransitive verb": ["Gorge oneself with food.", "Crowd together with other people in disorderly or dirty conditions.", "(of a sow) give birth to piglets; farrow.", "Operate a pig within an oil or gas pipeline."]}}
{"list": {"noun": ["A number of connected items or names written or printed consecutively, typically one below the other.", "A formal structure analogous to a list, by which items of data can be stored or processed in a definite order.", "Barriers enclosing an area for a jousting tournament.", "The scene of a contest or combat.", "A selvage of a piece of fabric.", "An instance of a ship leaning to one side.", "Desire or inclination."], "transitive verb": ["Make a list of.", "Include or enter in a list.", "Be on a list of products at (a specified price)", "Enlist for military service."], "intransitive verb": ["(of a ship) lean to one side, typically because of a leak or unbalanced cargo.", "Want; like."]}}
{"pigeon": {"noun": ["A stout seed- or fruit-eating bird with a small head, short legs, and a cooing voice, typically having gray and white plumage.", "A pigeon descended from the wild rock dove, kept for racing, showing, and carrying messages, and common as a feral bird in towns.", "A gullible person, especially someone swindled in gambling or the victim of a confidence trick.", "An aircraft from one's own side.", "archaic spelling of pidgin", "archaic spelling of pidgin"]}}
{"pike": {"noun": ["A long-bodied predatory freshwater fish with a pointed snout and large teeth, of both North America and Eurasia.", "Used in names of other predatory fish with large teeth, e.g., garpike.", "An infantry weapon with a pointed steel or iron head on a long wooden shaft.", "(in names) a hill with a peaked top.", "short for turnpike", "short for turnpike", "A position in diving or gymnastics in which the body is bent at the waist but the legs remain straight."], "transitive verb": ["Kill or thrust (someone) through with a pike."], "intransitive verb": ["Withdraw from or go back on (a plan or agreement).", "Let (someone) down."]}}
{"pinniped": {"noun": ["A carnivorous aquatic mammal of the order Pinnipedia, such as a seal or walrus."], "adjective": ["Relating to or denoting pinnipeds."]}}
{"piranha": {"noun": ["A deep-bodied South American freshwater fish that typically lives in schools and has very sharp teeth that are used to tear flesh from prey. It has a reputation as a fearsome predator."]}}
{"planarian": {"noun": ["A free-living flatworm which has a three-branched intestine and a tubular pharynx, typically located halfway down the body."]}}
{"pony": {"noun": ["A horse of a small breed, especially one whose height at the withers is below 14 hands 2 inches (58 inches).", "Racehorses.", "A small drinking glass or the drink contained in it.", "Twenty-five pounds sterling.", "A literal translation of a foreign-language text, used illicitly by students; a trot."], "transitive verb": ["Pay (money), especially as a contribution or an unavoidable expense."]}}
{"platypus": {"noun": ["A semiaquatic egg-laying mammal which frequents lakes and streams in eastern Australia. It has a sensitive pliable bill shaped like that of a duck, webbed feet with venomous spurs, and dense fur."]}}
{"porcupine": {"noun": ["A large rodent with defensive spines or quills on the body and tail."]}}
{"porpoise": {"noun": ["A small toothed whale with a low triangular dorsal fin and a blunt rounded snout."], "intransitive verb": ["Move through the water like a porpoise, alternately rising above it and submerging."]}}
{"possum": {"noun": ["An opossum.", "A tree-dwelling Australasian marsupial that typically has a prehensile tail."]}}
{"prawn": {"noun": ["A marine crustacean which resembles a large shrimp."]}}
{"primate": {"noun": ["The chief bishop or archbishop of a province.", "A mammal of an order that includes the lemurs, bushbabies, tarsiers, marmosets, monkeys, apes, and humans. They are distinguished by having hands, feet that are similar to hands, and forward-facing eyes, and, with the exception of humans, are typically agile tree-dwellers."]}}
{"wildcat": {"noun": ["A small native Eurasian and African cat that is typically gray with black markings and a bushy tail, noted for its ferocity.", "Any of the smaller members of the cat family, especially the bobcat.", "A hot-tempered or ferocious person (typically used of a woman).", "An exploratory oil well."], "adjective": ["(of a strike) sudden and unofficial.", "Commercially unsound or risky."], "intransitive verb": ["Prospect for oil."]}}
{"whitefish": {"noun": ["A mainly freshwater fish of the salmon family, widely used as food."]}}
{"wildfowl": {"plural noun": ["Game birds, especially aquatic ones; waterfowl."]}}
{"wildebeest": {"noun": ["A large dark African antelope with a long head, a beard and mane, and a sloping back."]}}
{"wolf": {"noun": ["A wild carnivorous mammal of the dog family, living and hunting in packs. It is native to both Eurasia and North America, but has been widely exterminated.", "Used in names of mammals similar or related to the wolf, e.g. maned wolf, Tasmanian wolf.", "Used figuratively to refer to a rapacious, ferocious, or voracious person or thing.", "A man who habitually seduces women.", "A harsh or out-of-tune effect produced when playing particular notes or intervals on a musical instrument, caused either by the instrument's construction or by divergence from equal temperament."], "transitive verb": ["Devour (food) greedily."]}}
{"wolverine": {"noun": ["A heavily built short-legged carnivorous mammal with a shaggy dark coat and a bushy tail, native to the tundra and forests of arctic and subarctic regions.", "A native or inhabitant of Michigan."]}}
{"wombat": {"noun": ["A burrowing plant-eating Australian marsupial which resembles a small bear with short legs."]}}
{"woodpecker": {"noun": ["A bird with a strong bill and a stiff tail, which climbs tree trunks to find insects and drums on dead wood to mark territory."]}}
{"worm": {"noun": ["Any of a number of creeping or burrowing invertebrate animals with long, slender soft bodies and no limbs.", "Intestinal or other internal parasites.", "Used in names of long slender insect larvae, especially those in fruit or wood, e.g. army worm, woodworm.", "Used in names of other animals that resemble worms in some way, e.g. slow-worm, shipworm.", "A maggot supposed to eat buried corpses.", "A weak or despicable person (used as a general term of contempt).", "A helical device or component.", "The threaded cylinder in a worm gear.", "The coiled pipe of a still in which the vapor is cooled and condensed.", "A self-replicating program able to propagate itself across a network, typically having a detrimental effect."], "verb": ["Move with difficulty by crawling or wriggling.", "Move (something) into a confined space by wriggling it.", "Insinuate one's way into.", "Obtain information from (someone) by cunning persistence.", "Treat (an animal) with a preparation designed to expel parasitic worms.", "Make (a rope) smooth by winding small cordage between the strands."], "abbreviation": ["Write-once read-many, denoting a type of computer memory device."]}}
{"wren": {"noun": ["A small short-winged songbird found chiefly in the New World.", "Any of a number of small songbirds that resemble the true wrens in size or appearance.", "(in the UK) a member of the former Women's Royal Naval Service."]}}
{"yak": {"noun": ["A large domesticated wild ox with shaggy hair, humped shoulders, and large horns, used in Tibet as a pack animal and for its milk, meat, and hide.", "Trivial or unduly persistent conversation."], "intransitive verb": ["Talk at length about trivial or boring subjects."]}}
{"alpaca": {"noun": ["A long-haired domesticated South American mammal related to the llama, valued for its wool.", "The wool of the alpaca.", "Fabric made from the wool of the alpaca, with or without other fibers."]}}
{"zebra": {"noun": ["An African wild horse with black-and-white stripes and an erect mane.", "A large butterfly with pale stripes on a dark background.", "A silvery-gold sea bream with vertical black stripes.", "A person whose characteristic garb is a black-and-white striped uniform, especially a football official or a convict."]}}
{"cat": {"noun": ["A small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws. It is widely kept as a pet or for catching mice, and many breeds have been developed.", "A wild animal of the cat family.", "Used in names of catlike animals of other families, e.g., ring-tailed cat.", "(particularly among jazz enthusiasts) a person, especially a man.", "short for catalytic converter", "short for catalytic converter", "short for catamaran", "short for catamaran"], "transitive verb": ["Raise (an anchor) from the surface of the water to the cathead."], "abbreviation": ["Computer-assisted (or -aided) testing.", "Clear air turbulence."]}}
{"cattle": {"plural noun": ["Large ruminant animals with horns and cloven hoofs, domesticated for meat or milk, or as beasts of burden; cows.", "Similar animals of a group related to domestic cattle, including yak, bison, and buffalo."]}}
{"chicken": {"noun": ["A domestic fowl kept for its eggs or meat, especially a young one.", "Meat from a chicken.", "A coward.", "A game in which the first person to lose nerve and withdraw from a dangerous situation is the loser."], "adjective": ["Cowardly."], "intransitive verb": ["Withdraw from or fail in something through lack of nerve."]}}
{"dog": {"noun": ["A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, nonretractable claws, and a barking, howling, or whining voice.", "A wild animal of the dog family.", "The male of an animal of the dog family, or of some other mammals such as the otter.", "A person regarded as unpleasant, contemptible, or wicked (used as a term of abuse)", "Used to refer to a person of a specified kind in a tone of playful reproof, commiseration, or congratulation.", "Used in various phrases to refer to someone who is abject or miserable, especially because they have been treated harshly.", "A woman regarded as unattractive.", "A thing of poor quality; a failure.", "A mechanical device for gripping.", "Feet."], "transitive verb": ["Follow (someone or their movements) closely and persistently.", "(of a problem) cause continual trouble for.", "Act lazily; fail to try one's hardest.", "Grip (something) with a mechanical device."]}}
{"donkey": {"noun": ["A domesticated hoofed mammal of the horse family with long ears and a braying call, used as a beast of burden; an ass.", "A stupid or foolish person."]}}
{"ferret": {"noun": ["A domesticated polecat kept as a pet or used, especially in Europe, for catching rabbits. It is typically albino or brown.", "A rare weasel-like animal (Mustela nigripes), found in grassland in the US."], "verb": ["(of a person) hunt with ferrets, typically for rabbits.", "Clear (a hole or area of ground) of rabbits with ferrets.", "Look around in a place or container in search of something.", "Search tenaciously for and find something."]}}
{"goldfish": {"noun": ["A small reddish-golden Eurasian carp, popular in ponds and aquariums. A long history of breeding in China and Japan has resulted in many varieties of form and color."]}}
{"gayal?s=t": {"noun": ["A domesticated ox used in South Asia."]}}
{"guppy": {"noun": ["A small, livebearing freshwater fish widely kept in aquariums. Native to tropical America, it has been introduced elsewhere to control mosquito larvae."]}}
{"horse": {"noun": ["A large plant-eating domesticated mammal with solid hoofs and a flowing mane and tail, used for riding, racing, and to carry and pull loads.", "An adult male horse; a stallion or gelding.", "A wild mammal of the horse family.", "Cavalry.", "A frame or structure on which something is mounted or supported, especially a sawhorse.", "A horizontal bar, rail, or rope in the rigging of a sailing ship for supporting something.", "A unit of horsepower.", "Heroin.", "An obstruction in a vein."], "transitive verb": ["Provide (a person or vehicle) with a horse or horses."]}}
{"koi": {"noun": ["A common carp of a large ornamental variety, originally bred in Japan."]}}
{"llama": {"noun": ["A domesticated pack animal of the camel family found in the Andes, valued for its soft woolly fleece.", "The wool of the llama.", "Cloth made from the wool of the llama."]}}
{"yak": {"noun": ["A large domesticated wild ox with shaggy hair, humped shoulders, and large horns, used in Tibet as a pack animal and for its milk, meat, and hide.", "Trivial or unduly persistent conversation."], "intransitive verb": ["Talk at length about trivial or boring subjects."]}}
{"sheep": {"noun": ["A domesticated ruminant animal with a thick woolly coat and (typically only in the male) curving horns. It is kept in flocks for its wool or meat, and is proverbial for its tendency to follow others in the flock.", "A wild mammal related to this, such as the argali, bighorn, and urial.", "A person who is too easily influenced or led.", "A person regarded as a protected follower of God.", "A member of a minister's congregation."]}}
{"cat": {"noun": ["A small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws. It is widely kept as a pet or for catching mice, and many breeds have been developed.", "A wild animal of the cat family.", "Used in names of catlike animals of other families, e.g., ring-tailed cat.", "(particularly among jazz enthusiasts) a person, especially a man.", "short for catalytic converter", "short for catalytic converter", "short for catamaran", "short for catamaran"], "transitive verb": ["Raise (an anchor) from the surface of the water to the cathead."], "abbreviation": ["Computer-assisted (or -aided) testing.", "Clear air turbulence."]}}
{"cattle": {"plural noun": ["Large ruminant animals with horns and cloven hoofs, domesticated for meat or milk, or as beasts of burden; cows.", "Similar animals of a group related to domestic cattle, including yak, bison, and buffalo."]}}
{"donkey": {"noun": ["A domesticated hoofed mammal of the horse family with long ears and a braying call, used as a beast of burden; an ass.", "A stupid or foolish person."]}}
{"dog": {"noun": ["A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, nonretractable claws, and a barking, howling, or whining voice.", "A wild animal of the dog family.", "The male of an animal of the dog family, or of some other mammals such as the otter.", "A person regarded as unpleasant, contemptible, or wicked (used as a term of abuse)", "Used to refer to a person of a specified kind in a tone of playful reproof, commiseration, or congratulation.", "Used in various phrases to refer to someone who is abject or miserable, especially because they have been treated harshly.", "A woman regarded as unattractive.", "A thing of poor quality; a failure.", "A mechanical device for gripping.", "Feet."], "transitive verb": ["Follow (someone or their movements) closely and persistently.", "(of a problem) cause continual trouble for.", "Act lazily; fail to try one's hardest.", "Grip (something) with a mechanical device."]}}
